# These are supported funding model platforms

github: tsvenbla # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: tsvenbla
open_collective: # Replace with a single Open Collective username
ko_fi: tsvenbla
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: tsvenbla
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://paypal.me/tsvenbla', 'https://donate.stripe.com/dR6dTt6A39116go3cc'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2'] 
