#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# Use the following command to generate a strong hash of your desired (already strong) password.
# grub-mkpasswd-pbkdf2 --iteration-count=1000000 --salt=256
set superusers="tsvenbla"
password_pbkdf2 tsvenbla grub.pbkdf2.sha512.1000000.DA<omitted>5B
